import { onGetSubscriptionPlan } from '@/actions/settings'
import React from 'react'
import Section from '../section-label'
import { Card, CardContent, CardDescription } from '../ui/card'
import { Check, CheckCircle2, Plus } from 'lucide-react'
import { pricingCards } from '../../constants/landing-page'
// import Modal from '../mondal'
// import SubscriptionForm from '../forms/settings/subscription-form'
import Image from 'next/image'